#!/bin/bash
echo "Images to remove"
docker images -a | grep -v "sonar\|kibana\|grafana\|base\|mysql\|centos\|3rdparty_oracle12_nb_empty\|jslintvalidator\|influxdb\|test_phpbe\|oraclelinux\|base_alpine_oraclejdk8\|3rdparty_oracle19_nb_empty"

docker rmi `docker images -a | grep -v "sonar\|kibana\|grafana\|base\|mysql\|centos\|3rdparty_oracle12_nb_empty\|jslintvalidator\|influxdb\|test_phpbe\|oraclelinux\|base_alpine_oraclejdk8\|3rdparty_oracle19_nb_empty" | awk '{print $3}' | tail -n +2` || true
echo "Still images saved"
docker images --format '{{.Repository}}:{{.Tag}}\t{{.ID}}'
